services:
  db:
    image: postgres:15
    container_name: meu-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cliente_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  flyway:
    image: flyway/flyway:11.13.2
    container_name: meu-flyway
    command: migrate
    volumes:
      - ./migrations:/flyway/sql
      - ./migrations/flyway.conf:/flyway/conf/flyway.conf
    depends_on:
      - db

volumes:
  postgres_data:
